version: '3.1'

services:
  public:
    image: katta2311/public:22
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: public_service
    ports:
    - 8082:8082
    working_dir: /opt/app
    networks:
    - ingress
  networks:
    ingress:
      external: true
