version: '3.1'

services:
  public:
    image: katta2311/public:22
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: public_service
    ports:
    - 8082:8082
    working_dir: /opt/app
#  deploy: # This will be considered only in docker swarm.
 #   replicas: 3
  #  update_config:
   #   parallelism: 1
    #  delay: 20s
    #restartPolicy:
     # condition: on-failure
      #delay: 10s
      #max_attempts: 5
  networks:
    name: ingress
